[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]
